apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-default-pvc
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: odoo-custom-pvc
#   labels:
#     app: odoo
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi


