apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/odoo-svc.service.yaml
- resources/odoo.deployment.yaml
- resources/pvc.yaml
images:
- name: nkirui2030/odoo-erp
  newTag: main
